image: node:10

pipelines:
  default:
    - step:
        name: Test
        caches:
          - node
        script:
          - yarn
          - yarn test
  branches:
    feature/*:
      - step:
          name: Build
          caches:
            - node
          script:
            - yarn
            - yarn build:dev
      - step:
          name: Deploy to dev bucket
          deployment: test
          caches:
            - node
          script:
            - echo API_URL=$DEV_API_URL > .env
            - yarn
            - yarn build:dev
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $DEV_S3_BUCKET
                LOCAL_PATH: $LOCAL_PATH
      - step:
          name: Deploy to staging
          deployment: staging
          trigger: manual
          caches:
            - node
          script:
            - echo API_URL=$STAGE_API_URL > .env
            - yarn
            - yarn build:stage
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $STAGE_S3_BUCKET
                LOCAL_PATH: $LOCAL_PATH
    master:
      - step:
          name: Deploy to production
          deployment: production
          caches:
            - node
          script:
            - echo API_URL=$PROD_API_URL > .env
            - yarn
            - yarn build:prod
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $PROD_S3_BUCKET
                LOCAL_PATH: $LOCAL_PATH
