image: node:10

pipelines:
  default:
    - step:
        name: Test
        script:
          - npm run test
  pull-requests:
      feature-*:
          - step:
              name: Feature branch build Test
              caches:
                - node
              script:
                - npm install
                - npm run build:dev
      fix-*:
          - step:
              name: Feature branch build Test
              caches:
                - node
              script:
                - npm install
                - npm run build
  branches:
    dev:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run build:dev
      - step:
          name: Deploy to dev bucket
          deployment: test
          caches:
            - node
          script:
              - pipe: atlassian/aws-s3-deploy:0.2.4
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  S3_BUCKET: $S3_BUCKET
                  LOCAL_PATH: $LOCAL_PATH
